const { buildPoseidon } = require("circomlibjs")
const dilithium = require("dilithium-crystals")
const fs = require("fs")

async function main() {
    const poseidon = await buildPoseidon()
    const F = poseidon.F

    // Load dilithium keys generated by register.js
    const keys = JSON.parse(fs.readFileSync("voter_keys.json"))
    const publicKey = new Uint8Array(keys.publicKey)

    const secretKey = BigInt(5)
    const age = BigInt(28)

    // Chunk dilithium public key into 16 field elements
    const pubKeyChunks = Array.from(publicKey)
        .slice(0, 16)
        .map(x => BigInt(x))

    // Compute all values
    const pk = poseidon([secretKey])
    const ageCommit = poseidon([age, secretKey])
    const dilKeyHash = poseidon(pubKeyChunks)

    const input = {
        secretKey: "5",
        age: "28",
        dilithiumPubKey: pubKeyChunks.map(x => x.toString()),
        publicKey: F.toString(pk),
        ageCommitment: F.toString(ageCommit),
        dilithiumKeyHash: F.toString(dilKeyHash),
        minAge: "18"
    }

    fs.writeFileSync("input.json", JSON.stringify(input, null, 2))
    console.log("input.json generated!")
    console.log(input)
}

main()